### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by xxSSSxx-1978** [dynamofoundation/MiningPool#1]
F:\_Miner\MiningPool-master\x64\Debug>MiningPool -mode stratum -server eu.letshash.it -port 5966 -user dy1qlgxtr6lqku2fgr02ynt4uu2tat289k8wxxxxxxx.xxx -pass d=2 -miner CPU,0,1,2
FATAL ERROR: Cannot open settings.txt

**Comment by dynamo-foundation** [comment]
It appears that you are trying to use the mining software.  This repo is for running mining pool.  Please check out dynminer binaries repo.
