### ISSUE TITLE
Pool: Feature list

### ISSUE THREAD

**Issue by scoobiru** [dynamofoundation/MiningPool#3]
Features separated into primary (+) and secondary (-)

miner
\+ shares accept/reject
\+ pending balance
\+ paid balance
\+ pool hash share percentage
\+ adjustable starting diff
\- pool block share percentage/amount
\- workerid delineation
\- miner found blocks
\- custom payout threshold

pool
\+ pool hash
\+ miner count
\+ found blocks
\- net hash
\- next payout time

admin
\+ pending mining balance
\+ pending payout balance
\- adjustable payout time
\- instant payout button
\- dual payout threshold
\- restart/shutdown service

**Comment by dynamo-foundation** [comment]
Add:
capture transaction hash when payout is run
ability to run sql from console and not lock up database
logging of attempted payouts and payout errors

**Comment by scoobiru** [comment]
updated list with:

pool - next payout time
admin - adjustable payout time

**Comment by dynamo-foundation** [comment]
Updated status and need clarification on some of these - let's open new project items on the board for each time and close this one

miner
+ shares accept/reject - DONE
+ pending balance - DONE
+ paid balance - DONE
+ pool hash share percentage - NEED CLARIFICATION
+ adjustable starting diff - DONE
- pool block share percentage/amount - DONE
- workerid delineation - NEED CLARIFICATION
- miner found blocks - DONE
- custom payout threshold - DONE

pool
+ pool hash - OPEN ITEM ON BOARD - NEED FORMULA/SOURCE
+ miner count - WILL OPEN NEW ITEM
+ found blocks - DONE
- net hash - OPEN ITEM ON BOARD - NEED FORMULA/SOURCE
- next payout time - DONE

admin
+ pending mining balance - WILL OPEN NEW ITEM
+ pending payout balance - WILL OPEN NEW ITEM
- adjustable payout time - DONE
- instant payout button - WILL OPEN NEW ITEM
- dual payout threshold - NEED CLARIFICATION
- restart/shutdown service - HARD TO DO - WILL OPEN ITEM BUT NEEDS MORE DETAILS AND THOUGHT
